logging:
  file: /var/log/webhookee/server.log
  level:
    in.picos.webhookee: DEBUG

endpoints:
  enabled: false
  health:
    enabled: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}