logging:
  file: /var/log/webhookee/server.log
  level:
    in.picos.webhookee: DEBUG

endpoints:
  enabled: false
  health:
    enabled: true

server:
  port: 80
  address: 0.0.0.0

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}