#https://github.com/spring-projects/spring-boot/tree/v1.5.15.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: webhookee
    properties:
      foo: bar