app:
  name: webhookee management server
  description: webhookee management server

server:
  port: 80
  address: 0.0.0.0

security:
  basic:
    enabled: false

spring:
  mvc:
    date-format: yyyy-MM-dd
    favicon:
      enabled: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.sss'Z'
    serialization:
      write-dates-as-timestamps: true
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/webhookee
  profiles:
    active: prd
