version: '2.1'
services:
  kafka:
    container_name: webhookee-kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    links:
      - "zookeeper:webhookee-zookeeper"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    container_name: webhookee-zookeeper
    image: zookeeper:3.4
    ports:
      - "2181:2181"
  mongodb:
    container_name: webhookee-mongodb
    image: mongo
    ports:
      - "27017:27017"
  redis:
    container_name: webhookee-redis
    image: redis:alpine
    ports:
      - "6379:6379"
