version: '2.1'
services:
  broker:
    container_name: webhookee-broker
    image: melthaw/webhookee:broker
    depends_on:
      - mongodb
      - rabbitmq
    links:
      - mongodb
      - rabbitmq
    ports:
      - "80:80"
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DB: webhookee
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

  rabbitmq:
    container_name: webhookee-rabbitmq
    image: rabbitmq:3-management

  mongodb:
    container_name: webhookee-mongodb
    image: mongo
    volumes:
      - "webhookee_mongodb:/data/db"

volumes:
  webhookee_mongodb: