version: '2.1'
services:
  broker:
    container_name: webhookee-broker
    build:
      context: broker
      dockerfile: docker/Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    links:
      - mongodb
      - rabbitmq
    ports:
      - "80:80"
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
  rabbitmq:
    container_name: webhookee-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  mongodb:
    container_name: webhookee-mongodb
    image: mongo
    ports:
      - "27017:27017"
