# https://github.com/spring-projects/spring-boot/blob/v1.5.15.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: secret